In [1]:
library("reticulate")
use_python("C:/Users/berkc/Miniconda3/envs/pytR_BNN", required = T)
# py_config()

In [28]:
source("sobolNN.r")
source("sobolGPmethods.R")
source("pickfreeze.R")
library(DiceKriging)

# Train NN model

In [29]:
# #--------------------------------------#
# # sobol samples & candidate points
# #--------------------------------------#
# n <- 100; d <- 2
# X1 <- data.frame(matrix(runif(d * n), nrow = n))
# X2 <- data.frame(matrix(runif(d * n), nrow = n))

# candidate <- data.frame(matrix(runif(d * 10), nrow = 10))

# Xb <- X2
# Xb[, 1] <- X1[, 1]
# X <- rbind(X1, Xb)
# nX <- dim(X)[1]
# X <- rbind(X, data.frame(candidate))

# source_python("simulateNN1.py")
# # ns = 5
# m <- pass_arg(5, X)
# m

In [71]:
# length(sim$samples)

In [72]:
# pred = py_run_file("predictNN.py")

In [73]:
# pred$samples

In [74]:
# pred$means

In [75]:
# m = py_run_file("trainNN.py")

In [76]:
# # names(m)
# model = m$net

In [32]:
#--------------------------------------#
# sobol samples & candidate points
#--------------------------------------#
d <- 2; n <- 2000
X1 <- data.frame(matrix(runif(d * n), nrow = n))
X2 <- data.frame(matrix(runif(d * n), nrow = n))

candidate <- data.frame(matrix(runif(d * 10), nrow = 10))

In [34]:
#--------------------------------------#
# Kriging-based Sobol
#--------------------------------------#
res <- sobolNN(
model = "NN",
type="UK",
MCmethod="sobol",
X1,
X2,
nsim = 200,
conf = 0.95,
nboot=1,
sequential = FALSE,
candidate,
sequential.tot=FALSE,
max_iter = 100
) 

res
# plot(res)
# x <- ask(res)
# y <- branin(x)
# The following line doesn't work (uncorrected bug: 
#     unused argument in km(), passed by update(), eval(), tell.sobolGP() ??)
#res.new <- tell(res,y,x)
#res.new



Method: sobol

Number of NN realizations: 200 

Kriging type: UK 

    estimate std. error min. c.i. max. c.i.
S1 0.2145465 0.01377064 0.1884674 0.2427428
S2 0.6065766 0.01164888 0.5828740 0.6299660


In [23]:
res


Method: sobol

Number of GP realizations: 10 

Kriging type: UK 

    estimate std. error min. c.i. max. c.i.
S1 0.2031658 0.04544303 0.1660901 0.3003247
S2 0.5955064 0.02940298 0.5517315 0.6340442


In [20]:
res$S

$S1
 [1] 0.16738968 0.10881299 0.13001468 0.15481020 0.11425221 0.15992314
 [7] 0.15326166 0.07829531 0.10229823 0.08207102

$S2
 [1] 0.5848682 0.5593256 0.5206500 0.5938354 0.5805747 0.6069536 0.5872275
 [8] 0.6775220 0.6146305 0.5947853

$xnew
[1] X1 X2
<0 rows> (or 0-length row.names)

$xnewi
integer(0)

$mean
          [,1]      [,2]
[1,] 0.1251129 0.5920373

$var
            [,1]       [,2]
[1,] 0.001071781 0.00160261

$ci
           [,1]      [,2]
[1,] 0.07914485 0.5293520
[2,] 0.16570971 0.6633714

$varPG
            [,1]       [,2]
[1,] 0.001071781 0.00160261

$varMC
     [,1] [,2]
[1,]   NA   NA

In [128]:
res[[2]]

[,1]      [,2]       [,3]      [,4]      [,5]        [,6]     
 [1,] 0.2506551 0.53566456 0.4324831 0.5905616 -0.18960640 0.3558713
 [2,] 0.2506551 0.45639923 0.6166791 0.4977939 -0.13127013 0.5299715
 [3,] 0.2506551 0.45639923 0.6166791 0.6920009  0.12420680 0.4879813
 [4,] 0.2506551 0.45639923 0.6166791 0.5905616 -0.13127013 0.3558713
 [5,] 0.2506551 0.45639923 0.6166791 0.5905616  0.11324847 0.3558713
 [6,] 0.3419454 0.45639923 0.4229008 0.5905616 -0.04354674 0.3558713
 [7,] 0.2506551 0.50966817 0.6729016 0.5905616 -0.13127013 0.5299715
 [8,] 0.2506551 0.05125561 0.6166791 0.4977939 -0.30624944 0.2217540
 [9,] 0.2506551 0.45639923 0.6166791 0.5905616 -0.13127013 0.2959754
[10,] 0.2506551 0.50966817 0.6166791 0.5905616 -0.18250743 0.3558713
      [,7]        [,8]      [,9]      [,10]     [,11] [,12]      [,13]      
 [1,]  0.06740497 0.4366664 0.2111532 0.5104985 <U+22EF> 0.33568260  0.25400853
 [2,]  0.05375142 0.4366664 0.2111532 0.5104985 <U+22EF> 0.36231941  0.38461483
 [3,]  0.17366806 0.5064692 0.1466544 0.5104985 <U+22EF> 0.26295340 -0.04372887
 [4,]  0.06740497 0.4971548 0.3089096 0.5104985 <U+22EF> 0.36231941 -0.04372887
 [5,]  0.06740497 0.5064692 0.3129236 0.5104985 <U+22EF> 0.36231941  0.36494353
 [6,] -0.05114549 0.5064692 0.2111532 0.3582557 <U+22EF> 0.04135349 -0.04372887
 [7,]  0.19949690 0.5064692 0.2111532 0.5104985 <U+22EF> 0.36231941  0.43878451
 [8,]  0.06740497 0.5732327 0.2111532 0.5104985 <U+22EF> 0.36231941  0.25400853
 [9,]  0.06740497 0.5064692 0.4285319 0.3683271 <U+22EF> 0.36231941  0.25400853
[10,]  0.06740497 0.4366664 0.4037485 0.6133035 <U+22EF> 0.36231941  0.15946937
      [,14]       [,15]     [,16]     [,17]     [,18]      [,19]     [,20]     
 [1,]  0.08833506 0.3441501 0.4676372 0.1441769 0.42244834 0.1205269 0.14306453
 [2,] -0.04744333 0.3441501 0.5964495 0.3249210 0.42244834 0.2917826 0.23047830
 [3,]  0.20406538 0.3441501 0.4725915 0.3437502 0.42244834 0.1886869 0.23047830
 [4,]  0.20406538 0.3441501 0.4676372 0.3249210 0.42244834 0.1886869 0.23047830
 [5,]  0.15232027 0.1915261 0.3982078 0.3249210 0.33322185 0.3881376 0.17250606
 [6,]  0.20406538 0.3441501 0.4676372 0.3249210 0.41157544 0.1790986 0.33142504
 [7,] -0.04744333 0.3441501 0.4748774 0.3249210 0.27051735 0.1886869 0.05906111
 [8,]  0.10152543 0.3441501 0.4676372 0.3885841 0.42244834 0.3005932 0.23047830
 [9,]  0.31333938 0.4459204 0.3982078 0.3249210 0.08655968 0.1050326 0.15886076
[10,]  0.20406538 0.3441501 0.4676372 0.3144762 0.42244834 0.1886869 0.11903501
      [,21]    
 [1,] 0.5929322
 [2,] 0.4155872
 [3,] 0.5929322
 [4,] 0.5929322
 [5,] 0.5929322
 [6,] 0.5171080
 [7,] 0.4552236
 [8,] 0.5929322
 [9,] 0.5929322
[10,] 0.5929322