In [1]:
library("reticulate")
# use_python("C:/Users/berkc/Miniconda3/envs/R", required = T)
use_python("C:/Users/kapusub/Anaconda3/envs/deep_learning_PIML", required = T)
py_config()

python:         C:/Users/kapusub/Anaconda3/envs/deep_learning_PIML/python.exe
libpython:      C:/Users/kapusub/Anaconda3/envs/deep_learning_PIML/python37.dll
pythonhome:     C:\Users\kapusub\ANACON~1\envs\DEEP_L~2
version:        3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\kapusub\ANACON~1\envs\DEEP_L~2\lib\site-packages\numpy
numpy_version:  1.18.1

NOTE: Python version was forced by use_python function

In [2]:
source("sobolGP_poro_np.R")
source("sobolGP_poro_np_upd.R")
source("sobolGPmethods.R")
source("pickfreeze.R")

# Pre-trained model parameters

In [3]:
gp = source_python("GP_pre_train.py")
params <- Gp_phy()
params

0.753**2 * RBF(length_scale=[0.471, 4.79, 0.889, 1.3e+05, 3.15e+04, 49.4, 1.67e+06, 9.39e+04, 2.01e+05, 4.19e+05, 6.5e+05])

In [6]:
# numobs <- c(500,1000,1500,2000,2500)
numobs <- c(100,250,500,750,1000)
case1 <- c("GP_MC_p_Lake","GP_loss_MC_p_Lake")
case2 <- c("GP_upd_MC_p_Lake","GP_upd_loss_MC_p_Lake")
# case1 <- c("GP_MC_p_Lake")
# case2 <- c()
# numobs <- c(250)

d <- 11; n <- 5000
candidate <- data.frame(matrix(runif(d * 2), nrow = 2))
X1 <- data.frame(matrix(runif(d * n), nrow = n))
X2 <- data.frame(matrix(runif(d * n), nrow = n))

for(j in case1){
    source("sobolGP_poro_np.R")
    GP_file = paste(j, ".py", sep="")
    GP_samplefile =  paste("Sample_",j, ".py", sep="")
    cat(GP_file,"\n")
    for(i in numobs){
    
        start_time <- Sys.time()
        #--------------------------------------#
        # Kriging-based Sobol
        #--------------------------------------#
        res <- sobolGP_poro_np(
        model = "GP",
        type="UK",
        MCmethod="sobol2002",
        X1,
        X2,
        nsim = 100,
        conf = 0.95,
        nboot=1,
        sequential = FALSE,
        candidate,
        sequential.tot=FALSE,
        max_iter = 100,
        filename1=GP_file,
        filename2=GP_samplefile,
        nobs = i
        )

        end_time <- Sys.time()
        print(end_time - start_time)
        
        # combine number of observation vector with Sobol indices
#         data <- cbind(i, res$S$mean)
        data <- cbind(i, res$S$mean, t(res$S$ci[1,]), t(res$S$ci[2,]))
        dat <- as.data.frame(data)
        
        # total index
#         dataT <- cbind(i, res$T$mean)
        dataT <- cbind(i, res$T$mean, t(res$T$ci[1,]), t(res$T$ci[2,]))
        datT <- as.data.frame(dataT)
        
        # write to file
        results_dir <- "../../../../results/Lake/"
        # filename <- paste(results_dir, "Case1_", toString(num_obs), ".csv", sep = "")
        # write.csv(x=dat, file=filename)
        # write.table(dat, file=filename, append=T)
        filename <- paste(results_dir, paste(j, "_first_", n,"_smallalpha.csv", sep=""), sep = "")
        write.table(dat, filename, sep = ",", col.names = !file.exists(filename), row.names = F, append = T)
        
        filenameT <- paste(results_dir, paste(j, "_tot_", n,"_smallalpha.csv", sep=""), sep = "")
        write.table(datT, filenameT, sep = ",", col.names = !file.exists(filenameT), row.names = F, append = T)
    }
}






for(j in case2){
    source("sobolGP_poro_np_upd.R")
    GP_file = paste(j, ".py", sep="")
    GP_samplefile =  paste("Sample_",j, ".py", sep="")
    cat(GP_file,"\n")
    for(i in numobs){
    
        start_time <- Sys.time()
        #--------------------------------------#
        # Kriging-based Sobol
        #--------------------------------------#
        res <- sobolGP_poro_np_upd(
        model = "GP",
        type="UK",
        MCmethod="sobol2002",
        X1,
        X2,
        nsim = 100,
        conf = 0.95,
        nboot=1,
        sequential = FALSE,
        candidate,
        sequential.tot=FALSE,
        max_iter = 100,
        filename1=GP_file,
        filename2=GP_samplefile,
        params,
        nobs = i
        )
        
        end_time <- Sys.time()
        print(end_time - start_time)
        
        # combine number of observation vector with Sobol indices
#         data <- cbind(i, res$S$mean)
        data <- cbind(i, res$S$mean, t(res$S$ci[1,]), t(res$S$ci[2,]))
        dat <- as.data.frame(data)
        
        # total index
#         dataT <- cbind(i, res$T$mean)
        dataT <- cbind(i, res$T$mean, t(res$T$ci[1,]), t(res$T$ci[2,]))
        datT <- as.data.frame(dataT)
        
        # write to file
        results_dir <- "../../../../results/Lake/"
        # filename <- paste(results_dir, "Case1_", toString(num_obs), ".csv", sep = "")
        # write.csv(x=dat, file=filename)
        # write.table(dat, file=filename, append=T)
        filename <- paste(results_dir, paste(j, "_first_", n,"_smallalpha.csv", sep=""), sep = "")
        write.table(dat, filename, sep = ",", col.names = !file.exists(filename), row.names = F, append = T)
        
        filenameT <- paste(results_dir, paste(j, "_tot_", n,"_smallalpha.csv", sep=""), sep = "")
        write.table(datT, filenameT, sep = ",", col.names = !file.exists(filenameT), row.names = F, append = T)
    }
}

GP_MC_p_Lake.py 
Time difference of 37.99489 mins


Warning message in write.table(dat, filename, sep = ",", col.names = !file.exists(filename), :
"appending column names to file"Warning message in write.table(datT, filenameT, sep = ",", col.names = !file.exists(filenameT), :
"appending column names to file"

Time difference of 38.17036 mins
Time difference of 38.66078 mins
Time difference of 39.63113 mins
Time difference of 40.17338 mins
GP_loss_MC_p_Lake.py 
Time difference of 38.11397 mins


Warning message in write.table(dat, filename, sep = ",", col.names = !file.exists(filename), :
"appending column names to file"Warning message in write.table(datT, filenameT, sep = ",", col.names = !file.exists(filenameT), :
"appending column names to file"

Time difference of 38.87633 mins
Time difference of 39.782 mins
Time difference of 42.15022 mins
Time difference of 42.8144 mins
GP_upd_MC_p_Lake.py 
Time difference of 36.81297 mins


Warning message in write.table(dat, filename, sep = ",", col.names = !file.exists(filename), :
"appending column names to file"Warning message in write.table(datT, filenameT, sep = ",", col.names = !file.exists(filenameT), :
"appending column names to file"

Time difference of 37.49862 mins
Time difference of 38.24325 mins
Time difference of 38.89053 mins
Time difference of 39.68981 mins
GP_upd_loss_MC_p_Lake.py 
Time difference of 36.82641 mins


Warning message in write.table(dat, filename, sep = ",", col.names = !file.exists(filename), :
"appending column names to file"Warning message in write.table(datT, filenameT, sep = ",", col.names = !file.exists(filenameT), :
"appending column names to file"

Time difference of 38.27045 mins
Time difference of 38.31265 mins
Time difference of 38.80831 mins
Time difference of 39.78646 mins


In [34]:
res$S

$S1
[1]  0.6151430  0.3286995 -0.3364426

$S2
[1] 1.09063999 0.95804609 0.06638231

$mean
          [,1]      [,2]
[1,] 0.2024666 0.7050228

$var
          [,1]      [,2]
[1,] 0.2383298 0.3102915

$ci
           [,1]      [,2]
[1,] -0.3031855 0.1109655
[2,]  0.6008208 1.0840103

$varPG
          [,1]      [,2]
[1,] 0.2383298 0.3102915

$varMC
     [,1] [,2]
[1,]   NA   NA